version: '3.8'
services:
  devcontainer:
    image: arulrajnet/vscode-pelican-devcontainer:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.12
        POETRY_VERSION": 1.8.3
    volumes:
      - ${PWD}/..:/workspace:cached
      - ~/Dropbox/workspace/ubuntu_home/.aws:/root/.aws:cached
      - ~/Dropbox/workspace/ubuntu_home/.ssh:/root/.ssh:cached
      - ~/Dropbox/workspace/ubuntu_home/.gitconfig:/root/.gitconfig:cached
    command: sleep infinity
